name: compute-yield-averages-every-day
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/cron-yield-average.yaml'
  schedule:
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: GET /api/cron/yield-average
        run: |
          curl --fail --verbose                                           \
               --url https://yield-borg.vercel.app/api/cron/yield-average \
               --header "Authorization: Bearer ${{ secrets.CRON_KEY }}"
