name: get-yields-every-hour
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflow/**'  
  schedule:
    - cron: '0 */1 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: GET /api/cron
        env:
          CRON_KEY: ${{ secrets.CRON_KEY }}
        run: |
          curl --verbose                                    \
               --url https://yield-borg.vercel.app/api/cron \
               --header "Authorization: Bearer $CRON_KEY" 
